server:
  servlet:
    context-path: /api
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password:
    # mysql8.0+ jdbc驱动需要添加cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mars?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

